name: cicd feasibility check
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script to Parse JSON
        run: |
          python ./cicd/script.py

      - name: Read the output.json content
        run: |
          ls
          cat ./output.json
          
